# app
server:
  port: 8088

# spring
spring:
  # devtools
  devtools:
    restart:
      enabled: true
  ## DataSource Config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///efservice?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化大小，最小，最大
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.shenhua119.leadservice.entity
  global-config:
    # 刷新mapper 调试神器
    db-config:
      # 主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: auto
      # 字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: 2
      # 数据库大写下划线转换
      capital-mode: true
      # 驼峰下划线转换
      column-underline: true
      # 刷新mapper 调试神器
      refresh-mapper: true


# 配置文件上传的临时路径
fastdfs-path:
  upload_location: D:\develop\upload
  server_ip: http://192.168.4.167/


# 日志
logging:
  file: efservice-logs/efservice.log
